my-properties:
  stringProperty: This is a string
  numberProperty: 10
  listOfStrings:
    - String one
    - String two
    - String three
  dataClass:
    name: Data Class
    number: 7
    flag: true
  listOfDataClasses:
    -
      name: Class One
      number: 1
      flag: true
    -
      name: Class Two
      number: 2
      flag: false